export const menuItems = [
	{ icon: 'home', selected: true, href: '/' },
	{ icon: 'bell', selected: false, href: '/notifications' },
	{ icon: 'message', selected: false, href: '/messages' },
	{ icon: 'heart', selected: false, href: '/bookmarks' },
	{ icon: 'user', selected: false, href: '/profile' },
	{ icon: 'cog', selected: false, href: '/settings' }
];

export const clients = {
	unkown: '/images/anonymous.png',
	equal: '/images/equal.png',
	astral: 'https://astral.ninja/icons/favicon-128x128.png',
	damus: 'https://damus.io/img/damus-nobg.svg',

	//No Logo yet.
	nostr_console: 'https://ui-avatars.com/api/?background=random&name=nostr_console',
	BIJA: 'https://ui-avatars.com/api/?background=random&name=BIJA',
	'nostrpy-web': 'https://ui-avatars.com/api/?background=random&name=nostrpy-web',
	Ranger: 'https://ui-avatars.com/api/?background=random&name=Ranger',
	'more-speech': 'https://ui-avatars.com/api/?background=random&name=more-speech',
	'node-red': 'https://ui-avatars.com/api/?background=random&name=node-red',
	nostrx: 'https://ui-avatars.com/api/?background=random&name=nostrx',
	halochat: 'https://ui-avatars.com/api/?background=random&name=halochat'
};

export const relays = [
	'wss://nostr.drss.io',
	'wss://nostr-relay-dev.wlvs.space',
	'wss://nostr.ethtozero.fr',
	'wss://relay.lexingtonbitcoin.org',
	'wss://nostr.robotechy.com',
	'wss://nostr.bongbong.com',
	'wss://nostr.datamagik.com',
	'wss://nostr.roundrockbitcoiners.com',
	'wss://nostr.rocks',
	'wss://nostr.bitcoiner.social',
	'wss://nostr.leximaster.com',
	'wss://relay.nostr.pro',
	'wss://nostr.jimc.me',
	'wss://nostr1.tunnelsats.com',
	'wss://nostr.walletofsatoshi.com',
	'wss://lv01.tater.ninja',
	'wss://relay.21spirits.io',
	'wss://relay.stoner.com',
	'wss://nostr.fly.dev',
	'wss://relay.ryzizub.com',
	'wss://nostr.d11n.net',
	'wss://nostr.gruntwerk.org',
	'wss://nostr.tunnelsats.com',
	'wss://nostr.einundzwanzig.space',
	'wss://relay.nostrid.com',
	'wss://nostr-relay.freedomnode.com',
	'wss://nostr-relay.digitalmob.ro',
	'wss://jiggytom.ddns.net',
	'wss://mule.platanito.org',
	'wss://nostr.supremestack.xyz',
	'wss://nostr.nymsrelay.com',
	'wss://nostr.digitalreformation.info',
	'wss://nostr.orangepill.dev',
	'wss://nostr1.starbackr.me',
	'wss://nostr-relay.untethr.me',
	'wss://nostr.shmueli.org',
	'wss://nostr-relay.schnitzel.world',
	'wss://relay.kronkltd.net',
	'wss://relay.oldcity-bitcoiners.info',
	'wss://nostr-2.zebedee.cloud',
	'wss://wizards.wormrobot.org',
	'wss://nostr.sectiontwo.org',
	'wss://nostr.nodeofsven.com',
	'wss://nostr.delo.software',
	'wss://no.str.cr',
	'wss://nostr-pub.wellorder.net',
	'wss://nostr.mado.io',
	'wss://nostr.8e23.net',
	'wss://relay.nostrmoto.xyz',
	'wss://relay.nostr.info',
	'wss://nostr.shawnyeager.net',
	'wss://nostr-relay.lnmarkets.com',
	'wss://nostr.xpersona.net',
	'wss://nostr-relay.trustbtc.org',
	'wss://nostr.utxo.lol',
	'wss://relay.nyx.ma',
	'wss://nostr-relay.derekross.me',
	'wss://sg.qemura.xyz',
	'wss://nostr.rdfriedl.com',
	'wss://nostr-dev.wellorder.net',
	'wss://nostr.zebedee.cloud',
	'wss://nostr.mwmdev.com',
	'wss://nostr.shadownode.org',
	'wss://nostr.satsophone.tk',
	'wss://nostr.radixrat.com',
	'wss://nostr.coinos.io',
	'wss://relay.cryptocculture.com',
	'wss://relay.sovereign-stack.org',
	'wss://nostr.actn.io',
	'wss://nostr.jiashanlu.synology.me',
	'wss://relay.farscapian.com',
	'wss://relay.nostr.express',
	'wss://nostr.sandwich.farm',
	'wss://nostr.openchain.fr',
	'wss://nostr.ono.re',
	'wss://nostrrelay.com',
	'wss://relay.nostr.ch',
	'wss://nostr.nordlysln.net',
	'wss://nostr.zerofeerouting.com',
	'wss://nostr-01.bolt.observer',
	'wss://relay.r3d.red',
	'wss://nostr.pobblelabs.org',
	'wss://nostr.oxtr.dev',
	'wss://nostr.cercatrova.me',
	'wss://nostr.yael.at',
	'wss://nostr.oooxxx.ml',
	'wss://nostr.mom',
	'wss://nostr.v0l.io',
	'wss://relay.nostropolis.xyz/websocket',
	'wss://nostr.rewardsbunny.com',
	'wss://nostr.orba.ca',
	'wss://relay.nostr.au',
	'wss://nostr.swiss-enigma.ch',
	'wss://relay.sendstr.com',
	'wss://nostr.slothy.win'
];
